Update bicepBuild.yml

diff --git a/.github/workflows/bicepBuild.yml b/.github/workflows/bicepBuild.yml
--- a/.github/workflows/bicepBuild.yml
+++ b/.github/workflows/bicepBuild.yml
@@ -25,6 +25,6 @@ jobs:
       run: bicep build ./main.bicep
 
     # Checks the result
-    - name: The job has succeeded
-      if: ${{ failure() }}
-      run: exit 1
+    #- name: The job has succeeded
+    #  if: ${{ failure() }}
+    #  run: exit 1
